### ISSUE TITLE
Problems with running 

### ISSUE THREAD

**Issue by bestemic** [dsonyy/projekt-gra#3]
During running diagonally, the character probably moves faster than on a straight line.

**Comment by Ether141** [comment]
I think it's illusion.

**Comment by dsonyy** [comment]
I haven't played this version yet but I suppose that:
- When the player goes horizontally, he moves e.g. 1 pixel right/left.
- When he goes vertically, he moves 1 pixel up/down too.
- When he goes diagonally, he combines that two moves and changes his position by about 1.41 px (the root of 2 multiplied by 1px).

**Comment by Ether141** [comment]
I carried out measurement, here is the result. I'm not sure it needs fix.

![szkic](https://user-images.githubusercontent.com/42118307/53117508-59632580-354b-11e9-9b0b-ff8ac968de3c.png)

**Comment by dsonyy** [comment]
OK, but @bestemic detected it so this tiny issue really exist. Math confirms it too. Fixing that shouldn't be any problem but it doesn't affect on the gameplay so much.
